# -*- coding: utf-8 -*-
from reparar.models import *
from levantamiento.models import *
from metrados.models import *

rps = [u"N/A",u"S/I",u"I DIRTEPOL - PIURA",u"II DIRTEPOL - CHICLAYO",u"III DIRTEPOL - TRUJILLO",u"IV DIRTEPOL - TARAPOTO",
	u"V DIRTEPOL - IQUITOS",u"VI DIRTEPOL - PUCALLPA",u"VII DIRTEPOL - LIMA",u"VIII DIRTEPOL - HUANCAYO",
	u"IX DIRTEPOL - AYACUCHO",u"X DIRTEPOL - CUSCO",u"X DIRTEPOL CUSCO - Secretaria",u"XI DIRTEPOL - AREQUIPA",
	u"XI DIRTEPOL - SECRETARIA",u"XII DIRTEPOL - PUNO",u"XIII DIRTEPOL - HUARAZ",u"XIV DIRTEPOL - CAJAMARCA",u"XV DIRTEPOL - ICA",
	u"XVI DIRTEPOL - APURIMAC",u"XVII DIRTEPOL - PASCO",u"XVIII DIRTEPOL - TUMBES",u"XIX DIRTEPOL - HUANUCO",u"XX DIRTEPOL - CALLAO"
]

for rp in rps:
	RegionPolicial.objects.create(region=rp)

dpss = [u"DIPOPS01",u"DIPOPS02",u"DIPOPS03",u"DIPOPS04",u"DIPOPS05",u"DIPOPS06",u"DIPOPS07",u"DIPOPS08",u"DIPOPS09",u"DIPOPS10",
	u"DIPOPS11",u"DIPOPS12",u"DIPOPS13",u"DIPOPS14",u"DIPOPS15",u"DIPOPS16",u"DIPOPS17",u"DIPOPS18",u"DIPOPS19",u"DIPOPS20",
	u"DIPOPS21",u"DIPOPS22",u"DIPOPS23",u"DIPOPS24",u"DIPOPS25",u"DIPOPS26",u"DIPOPS27",u"DIPOPS28",u"DIPOPS29",u"DIPOPS30",
	u"DIPOPS31"
]

for dps in dpss:
	DivisionPolicial.objects.create(division=dps)

tcs = [u"Tipo A",u"Tipo B",u"Tipo C",u"Tipo D",u"Tipo E"]


for tc in tcs:
	TComisaria.objects.create(tipo=tc)

ccs = [u"BÁSICA",u"ESPECIALIZADA"]

for cc in ccs:
	CComisaria.objects.create(clase=cc)

eps =[u"FAMILIA",u"TURISMO",u"AEROP. Y TERMINAL TERRE.",u"CARRETERAS",u"OTROS"]

for ep in eps:
	Especialidad.objects.create(especialidad=ep)


cats = [u"SECTORIAL",u"LOCAL",u"DISTRITAL",u"OTROS"]

for cat in cats:
	Category.objects.create(category=cat)

sls =[u"PROPIO - MININTER",u"PROPIO - PNP",u"ALQUILADO",u"AFECTADO EN USO",u"CEDIDO EN USO",u"OTRO"]

for sl in sls:
	SituacionLegal.objects.create(situacion=sl)


tts = [u"ALIGERADO",u"CONCRETO ARMADO",u"MADERA",u"TEJAS",u"PLANCHAS DE CALAMINA O FIBROCEMENTO",u"OTROS"]

for tt in tts:
	TipoDeTecho.objects.create(tipo=tt)


gs = [u"GENERAL PNP",u"CORONEL PNP",u"COMANDANTE PNP",u"MAYOR PNP",u"CAPITAN PNP",u"SO1 PNP",u"SO2 PNP",u"SO3 PNP",u"Otro"]

for g in gs:
	Grado.objects.create(grado=g)

ests = [u"Pendiente",u"Levantamiento de Información",u"Elaboración de expedientes tecnicos",u"Proceso Logistico",
	u"Proceso de ejecución",u"Ejecutado",u"Verficado",u"Supendido",u"Cancelado"
]

for est in ests:
	EstadoDeEjecucion.objects.create(estado=est)

trs = [u"Requiere canaleta",u"Requiere hermetizar",u"Requiere proteger",u"Requiere reemplazar"]

for tr in trs:
	TReparacion.objects.create(reparacion=tr)

trs = [u"Requieren Tanque Cisterna",u"Limpieza y desinfección de cisternas, tanques elevados (total)",
	u"Requieren reparación de redes de agua (metro lineal)",u"Requiere reparar redes de desague",u"Reparación de pozo tubular (total)",
	u"Otros"
]

for tr in trs:
	ISReparacion.objects.create(reparacion=tr)

trs = [u"Cambio o reposición de interruptores (Und.)",u"Cambio o reposición de tomacorrientes (Und.)",
	u"Cambio o reposición de llaves térmicas (Und.)",u"Cambio de cables eléctricos",u"Mantenimiento de pozo a tierra. (total)",
	u"Protección de instalaciones eléctricas",u"Remplazo de luminarias",u"Otros"
]

for tr in trs:
	IEReparacion.objects.create(reparacion=tr)

trs = [u"Construcción de muros de contención",u"Reparación de muros de contención",U"Construcción de diques",
	u"Reparación de diques",u"Construcción de paredes",u"Reparación de paredes",u"Otros"
]

for tr in trs:
	MPReparacion.objects.create(reparacion=tr)

trs = [u"A",u"B","C",u"D",u"E"]

for tr in trs:
	VEReparacion.objects.create(reparacion=tr)

ues = [u"N/A",u"S/I",u"002-26: Direccion De Economia y Finanzas De La PNP",u"005-29: III Dirtepol - Trujillo",
	u"009-33: VII Dirección Territorial de Policía- Lima",u"010-34: VIII Dirección Territorial De Policía - Huancayo",
	u"012-36: X Dirección Territorial de Policía - Cusco",u"018-42: Direccion de Aviacion Policial",
	u"019-43: Dirección Ejecutiva de Educación Y Doctrina PNP-DIREDUD PNP",u"020-1067: Sanidad de la PNP",
	u"022-1147: PNP - XI Dirección Territorial De Policía - Arequipa",u"026-1312: Dirección Ejecutiva De Investigación Criminal Y Apoyo a la Justicia PNP- DIREICAJ PNP",
	u"028-1342: II Dirección Territorial de Policía Chiclayo",u"029-1343: Dirección Ejecutiva Antidrogas- DIREJANDRO PNP"
]

for ue in ues:
	UnidadEjecutora.objects.create(unidad=ue)

tis = ["Oficinas Administrativas","Unidades Especializadas","Comisarias","Centros de Salud","Centro Educativo"]

for ti in tis:
	Instalacion.objects.create(instalacion=ti)

mts1 = [[u"OE.1",u"OBRAS PROVISIONALES, TRABAJOS PRELIMINARES, SEGURIDAD Y SALUD."],[u"OE.2",u"ESTRUCTURAS."],
	[u"OE.3",u"ARQUITECTURA."],[u"OE.4",u"INSTALACIONES SANITARIAS."],[u"OE.5",u"INSTALACIONES ELÉCTRICAS Y MECÁNICAS."],
	[u"OE.6",u"INSTALACIONES DE COMUNICACIONES."],[u"OE.7",u"INSTALACIONES DE GAS."]
]

for codigo1,descripcion1 in mts1:
	Metrado1.objects.create(codigo=codigo1,descripcion=descripcion1)

mts2 = [[u"OE.1.1",u"OBRAS PROVISIONALES Y TRABAJOS PRELIMINARES",1],[u"OE.1.2",u"SEGURIDAD Y SALUD ",1],
	[u"OE.2.1",u"MOVIMIENTO DE TIERRAS ",2],[u"OE.2.2",u"OBRAS DE CONCRETO SIMPLE ",2],[u"OE.2.3",u"OBRAS DE CONCRETO ARMADO ",2],
	[u"OE.2.4",u"ESTRUCTURAS METÁLICAS ",2],[u"OE.2.5",u"ESTRUCTURA DE MADERA ",2],[u"OE.2.6",u"VARIOS ",2],
	[u"OE.3.1",u"MUROS Y TABIQUES DE ALBAÑILERIA ",3],[u"OE.3.2",u"REVOQUES Y REVESTIMIENTOS ",3],[u"OE.3.3",u"CIELORRASOS ",3],
	[u"OE.3.4",u"PISOS Y PAVIMENTOS ",3],[u"OE.3.5",u"ZOCALOS Y CONTRAZÓCALOS",3],[u"OE.3.6",u"COBERTURAS ",3],
	[u"OE.3.7",u"CARPINTERIA DE MADERA ",3],[u"OE.3.8",u"CARPINTERÍA METÁLICA Y HERRERÍA ",3],[u"OE.3.9",u"CERRAJERÍA ",3],
	[u"OE.3.10",u"VIDRIOS,CRISTALES Y SIMILARES ",3],[u"OE.3.11",u"BLOQUES DE VIDRIO ",3],[u"OE.3.12",u"VARIOS, LIMPIEZA, JARDINERÍA ",3],
	[u"OE.3.13",u"OTROS ",3],[u"OE.4.1",u"APARATOS SANITARIOS Y ACCESORIOS ",4],[u"OE.4.2",u"SISTEMA DE AGUA FRIA ",4],
	[u"OE.4.3",u"SISTEMA DE AGUA CALIENTE ",4],[u"OE.4.4",u"SISTEMA CONTRA INCENDIO ",4],[u"OE.4.5",u"SISTEMA DE DRENAJE PLUVIAL ",4],
	[u"OE.4.6",u"DESAGÜE Y VENTILACIÓN ",4],[u"OE.4.7",u"VARIOS ",4],[u"OE.5.1",u"CONEXIÓN A LA RED EXTERNA DE MEDIDORES ",5],
	[u"OE.5.2",u"SALIDAS PARA ALUMBRADO, TOMACORRIENTES, FUERZA Y SEÑALES DÉBILES ",5],[u"OE.5.3",u"INSTALACION DE PARARRAYOS ",5],
	[u"OE.5.4",u"INSTALACIÓN DEL SISTEMA DE PUESTA A TIERRA ",5],[u"OE.5.5",u"ARTEFACTOS ",5],
	[u"OE.5.6",u"EQUIPOS ELECTRICOS Y MECANICOS ",5],[u"OE.6.1",u"CABLEADO ESTRUCTURADO EN INTERIORES DE EDIFICIOS ",6],
	[u"OE.6.2",u"CANALETAS, CONDUCTOS Y/O TUBERÍAS ",6],[u"OE.6.3",u"SALIDA DE COMUNICACIONES ",6],
	[u"OE.6.4",u"CONDUCTORES DE COMUNICACIONES ",6],[u"OE.6.5",u"PATCH PANEL ",6],[u"OE.6.6",u"RACK DE COMUNICACIONES ",6],
	[u"OE.6.7",u"CAJA DE PASE PARA TRANSFORMADOR",6],[u"OE.7.1",u"TUBERÍAS ",7],[u"OE.7.2",u"ARTEFACTOS (GAS LICUADO DE PETRÓLEO Ó GAS NATURAL SECO)",7],
	[u"OE.7.3",u"ACCESORIOS ",7],[u"OE.7.4",u"VENTILACIONES ",7],[u"OE.7.5",u"DUCTOS ",7],[u"OE.7.6",u"GABINETE DE REGULACIÓN",7]
]

for codigo2,descripcion2,m1_id in mts2:
	m1 = Metrado1.objects.get(id=m1_id)
	m1.metrado_2.create(codigo=codigo2,descripcion=descripcion2)

mts3 = [[u"OE.1.1.1",u"CONSTRUCCIONES PROVISIONALES",1],
	[u"OE.1.1.2",u"INSTALACIONES PROVISIONALES ",1],
	[u"OE.1.1.3",u"TRABAJOS PRELIMINARES",1],
	[u"OE.1.1.4",u"ELIMINACIÓN DE OBSTRUCCIONES ",1],
	[u"OE.1.1.5",u"REMOCIONES ",1],
	[u"OE.1.1.6",u"DEMOLICIONES ",1],
	[u"OE.1.1.7",u"MOVILIZACIÓN DE CAMPAMENTO, MAQUINARIA Y HERRAMIENTAS  ",1],
	[u"OE.1.1.8",u"APUNTALAMIENTOS DE CONSTRUCCIONES EXISTENTES",1],
	[u"OE.1.1.9",u"TRAZOS, NIVELES Y REPLANTEO ",1],
	[u"OE.1.2.1",u"ELABORACIÓN, IMPLEMENTACIÓN Y ADMINISTRACIÓN DEL PLAN D SEGURIDAD Y SALUD EN EL TRABAJO ",2],
	[u"OE.1.2.2",u"RECURSOS PARA RESPUESTAS ANTE EMERGENCIAS EN SEGUR!  SALUD DURANTE EL TRABAJO ",2],
	[u"OE.2.1.1",u"NIVELACIÓN DE TERRENO ",3],
	[u"OE.2.1.2",u"EXCAVACIONES ",3],
	[u"OE.2.1.3",u"CORTES ",3],
	[u"OE.2.1.4",u"RELLENOS ",3],
	[u"OE.2.1.5",u"NIVELACIÓN INTERIOR Y APISONADO ",3],
	[u"OE.2.1.6",u"ELIMINACIÓN DE MATERIAL EXCEDENTE ",3],
	[u"OE.2.1.7",u"TABLAESTACADO O ENTIBADO ",3],
	[u"OE.2.2.1",u"CIMIENTOS CORRIDOS ",4],
	[u"OE.2.2.2",u"SUB ZAPATAS O FALSA ZAPATA ",4],
	[u"OE.2.2.3",u"SOLADOS ",4],
	[u"OE.2.2.4",u"BASES DE CONCRETO ",4],
	[u"OE.2.2.5",u"ESTRUCTURAS DE SOSTENIMIENTO DE EXCAVACIONES",4],
	[u"OE.2.2.6",u"SOBRECIMIENTOS",4],
	[u"OE.2.2.7",u"GRADAS ",4],
	[u"OE.2.2.8",u"RAMPAS",4],
	[u"OE.2.2.9",u"FALSOPISO",4],
	[u"OE.2.3.1",u"CIMIENTOS REFORZADOS ",5],
	[u"OE.2.3.2",u"ZAPATAS ",5],
	[u"OE.2.3.3",u"VIGAS DE CIMENTACIÓN ",5],
	[u"OE.2.3.4",u"LOSAS DE CIMENTACIÓN ",5],
	[u"OE.2.3.5",u"SOBRECIMIENTOS REFORZADOS ",5],
	[u"OE.2.3.6",u"MUROS REFORZADOS ",5],
	[u"OE.2.3.7",u"COLUMNAS ",5],
	[u"OE.2.3.8",u"VIGAS ",5],
	[u"OE.2.3.9",u"LOSAS ",5],
	[u"OE.2.3.10",u"ESCALERAS ",5],
	[u"OE.2.3.11",u"CAJA DE ASCENSORES Y SIMILARES ",5],
	[u"OE.2.3.12",u"CISTERNAS SUBTERRÁNEAS ",5],
	[u"OE.2.3.13",u"TANQUES ELEVADOS ",5],
	[u"OE.2.3.14",u"PILOTES ",5],
	[u"OE.2.3.15",u"CAISSONES ",5],
	[u"OE.2.3.16",u"ESTRUCTURAS DE CONCRETO PRETENSADO O POSTENSADO ",5],
	[u"OE.2.3.17",u"ESTRUCTURAS PREFABRICADAS ",5],
	[u"OE.2.4.1",u"COLUMNAS O PILARES ",6],
	[u"OE.2.4.2",u"VIGAS ",6],
	[u"OE.2.4.3",u"VIGUETAS ",6],
	[u"OE.2.4.4",u"TIJERALES Y RETICULADOS ",6],
	[u"OE.2.4.5",u"CORREAS ",6],
	[u"OE.2.4.6",u"COBERTURAS ",6],
	[u"OE.2.4.7",u"ELEMENTOS PARA AGUAS PLUVIALES ",6],
	[u"OE.2.5.1",u"COLUMNAS O PILARES ",7],
	[u"OE.2.5.2",u"VIGAS ",7],
	[u"OE.2.5.3",u"TIJERALES Y RETICULADOS ",7],
	[u"OE.2.5.4",u"CORREAS ",7],
	[u"OE.2.5.5",u"COBERTURAS ",7],
	[u"OE.2.5.6",u"PILOTES DE MADERA ",7],
	[u"OE.2.6.1",u"JUNTAS ",8],
	[u"OE.3.1.1",u"MUROS DE LADRILLO KING KONG DE ARCILLA (A MAQUINA O ARTESANALMENTE). ",9],
	[u"OE.3.1.2",u"MUROS DE LADRILLO CORRIENTE DE ARCILLA (A MAQUINA O ARTESANALMENTE) ",9],
	[u"OE.3.1.3",u"MUROS DE LADRILLO PANDERETA DE ARCILLA ",9],
	[u"OE.3.1.4",u"MUROS DE BLOCK SÍLICO-CALCÁREO K.K. STANDARD ",9],
	[u"OE.3.1.5",u"MUROS DE BLOCK SÍLICO-CALCÁREO TABIQUES (TRES HUECOS) ",9],
	[u"OE.3.1.6",u"MUROS DE LADRILLO DE CONCRETO ",9],
	[u"OE.3.1.7",u"MUROS DE BLOQUES HUECOS DE CONCRETO ",9],
	[u"OE.3.1.8",u"MUROS DE ALBAÑILERÍA ARMADA ",9],
	[u"OE.3.1.9",u"MUROS DE ALBAÑILERÍA CONFINADA ",9],
	[u"OE.3.1.10",u"MUROS CON EL SISTEMA DE CONSTRUCCIÓN EN SECO (SISTEMA DRY WALL O SIMILAR) ",9],
	[u"OE.3.1.11",u"MUROS DE PIEDRA ",9],
	[u"OE.3.1.12",u"MUROS DE ADOBE (SIMPLE O ESTABILIZADO) ",9],
	[u"OE.3.1.13",u"TABIQUES CON ELEMENTOS LEVES (FIBROCEMENTO, QUINCHA, ETC.) ",9],
	[u"OE.3.1.14",u"OTROS TIPOS DE MUROS O TABIQUES",9],
	[u"OE.3.1.15",u"BARANDAS Y PARAPETOS ",9],
	[u"OE.3.1.16",u"ARCOS ",9],
	[u"OE.3.1.17",u"ESTUFAS ",9],
	[u"OE.3.1.18",u"ACEROS DE AMARRE ",9],
	[u"OE.3.2.1",u"TARRAJEO RAYADO PRIMARIO ",10],
	[u"OE.3.2.2",u"TARRAJEO EN INTERIORES ",10],
	[u"OE.3.2.3",u"TARRAJEO EN EXTERIORES ",10],
	[u"OE.3.2.4",u"TARRAJEO FINO ",10],
	[u"OE.3.2.5",u"TARRAJEO EN COLUMNAS ",10],
	[u"OE.3.2.6",u"TARRAJEO EN VIGAS ",10],
	[u"OE.3.2.7",u"TARRAJEO DE MUROS DE CONCRETO ",10],
	[u"OE.3.2.8",u"TARRAJEO CON IMPERMEABILIZANTES ",10],
	[u"OE.3.2.9",u"TARRAJEO SALPICADO O ESCARCHADO",10],
	[u"OE.3.2.10",u"TARRAJEO ESPECIALES ",10],
	[u"OE.3.2.11",u"VESTIDURAS DE DERRAMES ",10],
	[u"OE.3.2.12",u"VESTIDURA DE ELEMENTOS DE FACHADA ",10],
	[u"OE.3.2.13",u"EMPASTADO DE MUROS DE ADOBE ",10],
	[u"OE.3.2.14",u"TARRAJEO SOBRE MALLA METÁLICA EN MUROS DE ADOBE ",10],
	[u"OE.3.2.15",u"TARRAJEO DE DUCTOS",10],
	[u"OE.3.2.16",u"ENLUCIDO DE YESO ",10],
	[u"OE.3.2.17",u"ENLUCIDO DE CUARZO EN PARAMENTO",10],
	[u"OE.3.2.18",u"UNIÓN DE MUROS Y CIELORRASO ",10],
	[u"OE.3.2.19",u"BRUÑAS ",10],
	[u"OE.3.2.20",u"TARRAJEO EN FONDO DE ESCALERA ",10],
	[u"OE.3.2.21",u"PREPARACIÓN DE GRADAS DE CONCRETO ",10],
	[u"OE.3.2.22",u"PREPARACIÓN DE DESCANSOS ",10],
	[u"OE.3.2.22",u"GRADAS ",10],
	[u"OE.3.2.23",u"DESCANSOS ",10],
	[u"OE.3.2.24",u"ENCHAPES ",10],
	[u"OE.3.3.1",u"CIELORRASO CON YESO ",11],
	[u"OE.3.3.2",u"YESO EN VIGAS ",11],
	[u"OE.3.3.3",u"CIELORRASO CON MEZCLA ",11],
	[u"OE.3.3.4",u"CIELORRASO PEGADO ",11],
	[u"OE.3.3.5",u"CIELORRASO CON EL SISTEMA DE CONSTRUCCIÓN EN SECO",11],
	[u"OE.3.3.6",u"FALSO CIELORRASO",11],
	[u"OE.3.4.1",u"CONTRAPISOS",12],
	[u"OE.3.4.2",u"PISOS ",12],
	[u"OE.3.4.3",u"PISOS DE CONCRETO ",12],
	[u"OE.3.4.4",u"ACABADO DE CONCRETO EN PISOS ",12],
	[u"OE.3.4.5",u"SARDINELES",12],
	[u"OE.3.4.6",u"VEREDAS ",12],
	[u"OE.3.4.7",u"PISTAS ",12],
	[u"OE.3.4.8",u"SOBREPISO O PISO TÉCNICO",12],
	[u"OE.3.5.1",u"ZOCALOS",13],
	[u"OE.3.5.2",u"CONTRAZOCALOS ",13],
	[u"OE.3.6.1",u"COBERTURA DE TORTA DE BARRO ",14],
	[u"OE.3.6.2",u"LADRILLO PASTELERO SOBRE TORTA DE BARRO ",14],
	[u"OE.3.6.3",u"LADRILLO PASTELERO SOBRE MORTERO ",14],
	[u"OE.3.6.4",u"MATERIAL IMPERMEABILIZANTE ",14],
	[u"OE.3.6.5",u"RECUBRIMIENTOS SOBRE ESTRUCTURA  DE MADERA, METAL, ETC. ",14],
	[u"OE.3.6.6",u"RECUBRIMIENTOS CON PLANCHAS METALICAS ",14],
	[u"OE.3.6.7",u"RECUBRIMIENTOS CON PANELES TERMO-ACÚSTICOS",14],
	[u"OE.3.6.8",u"RECUBRIMIENTOS DE MANTO ASFÁLTICO ",14],
	[u"OE.3.6.9",u"OTROS ",14],
	[u"OE.3.7.1",u"PUERTAS ",15],
	[u"OE.3.7.2",u"VENTANAS ",15],
	[u"OE.3.7.3",u"PERSIANAS DE MADERA ",15],
	[u"OE.3.7.4",u"MAMPARAS ",15],
	[u"OE.3.7.5",u"FORRO DE VANOS ",15],
	[u"OE.3.7.6",u"DIVISIONES PARA SERVICIOS HIGIÉNICOS ",15],
	[u"OE.3.7.7",u"DIVISIÓN ORNAMENTAL DE AMBIENTES ",15],
	[u"OE.3.7.8",u"TABIQUES DE MADERA ",15],
	[u"OE.3.7.9",u"ESCALERAS DE MADERA ",15],
	[u"OE.3.7.10",u"BARANDAS ",15],
	[u"OE.3.7.11",u"PASAMANOS AISLADOS ",15],
	[u"OE.3.7.12",u"MUEBLES DE COCINA Y SIMILARES ",15],
	[u"OE.3.7.13",u"VITRINAS ",15],
	[u"OE.3.7.14",u"CLOSET ",15],
	[u"OE.3.8.1",u"VENTANAS DE FIERRO ",16],
	[u"OE.3.8.2",u"PUERTAS DE FIERRO ",16],
	[u"OE.3.8.3",u"MAMPARAS DE FIERRO ",16],
	[u"OE.3.8.4",u"VENTANAS DE ALUMINIO ",16],
	[u"OE.3.8.5",u"PUERTAS DE ALUMINIO ",16],
	[u"OE.3.8.6",u"MAMPARAS DE ALUMINIO ",16],
	[u"OE.3.8.7",u"CELOSÍAS DE ALUMINIO ",16],
	[u"OE.3.8.8",u"CORTINAS ENROLLABLES DE FIERRO ",16],
	[u"OE.3.8.9",u"PUERTAS PLEGABLES DE FIERRO ",16],
	[u"OE.3.8.10",u"PUERTAS DE PLANCHA METÁLICA ",16],
	[u"OE.3.8.11",u"PUERTAS DE FIERRO Y MALLA ",16],
	[u"OE.3.8.12",u"DIVISIÓN DE PLANCHA DE ACERO GALVANIZADO PARA SERVICIOS HIGIÉNICOS ",16],
	[u"OE.3.8.13",u"DIVISIÓN DE ALUMINIO PARA SERVICIOS HIGIÉNICOS ",16],
	[u"OE.3.8.14",u"BARANDAS METÁLICAS ",16],
	[u"OE.3.8.15",u"PASAMANOS AISLADOS ",16],
	[u"OE.3.8.16",u"CERCOS DE FIERRO ",16],
	[u"OE.3.8.17",u"ESCALERAS METÁLICAS ",16],
	[u"OE.3.8.18",u"ELEMENTOS METÁLICOS ESPECIALES ",16],
	[u"OE.3.9.1",u"BISAGRAS ",17],
	[u"OE.3.9.2",u"CERRADURAS ",17],
	[u"OE.3.9.3",u"SISTEMAS O MECANISMOS ",17],
	[u"OE.3.9.4",u"ACCESORIOS DE CIERRE ",17],
	[u"OE.3.9.5",u"ACCESORIOS EN GENERAL ",17],
	[u"OE.3.9.6",u"CERRAJERÍA PARA MUEBLES ",17],
	[u"OE.3.10.1",u"ESPEJOS",18],
	[u"OE.3.10.2",u"VITRAL ",18],
	[u"OE.3.11.1",u"PINTURA ",19],
	[u"OE.3.11.2",u"PINTURA DE CIELOS RASOS, VIGAS, COLUMNAS Y PAREDES PINTURA DE PUERTAS. ",19],
	[u"OE.3.11.3",u"PINTURA DE VENTANAS. ",19],
	[u"OE.3.11.4",u"PINTURA DE ENCHAPES. ",19],
	[u"OE.3.11.5",u"PINTURA DE CONTRAZÓCALOS Y BARANDAS. ",19],
	[u"OE.3.11.6",u"PINTURA DE ESTRUCTURAS METÁLICAS. ",19],
	[u"OE.3.12.1",u"LIMPIEZA PERMANENTE DE OBRA ",20],
	[u"OE.3.12.2",u"LIMPIEZA FINAL ",20],
	[u"OE.3.12.3",u"LIMPIEZA DE VIDRIOS ",20],
	[u"OE.3.12.4",u"ENCERADOS DE PISOS ",20],
	[u"OE.3.12.5",u"SEMBRÍO DE GRASS ",20],
	[u"OE.3.12.6",u"TRABAJOS DE JARDINERÍA ",20],
	[u"OE.3.13.1",u"PODIO DE CONCRETO ",21],
	[u"OE.4.1.1",u"SUMINISTRO DE APARATOS SANITARIOS ",22],
	[u"OE.4.1.2",u"SUMINISTRO DE ACCESORIOS ",22],
	[u"OE.4.1.3",u"INSTALACIÓN DE APARATOS SANITARIOS ",22],
	[u"OE.4.1.4",u"INSTALACIÓN DE ACCESORIOS",22],
	[u"OE.4.2.1",u"SALIDA DE AGUA FRÍA ",23],
	[u"OE.4.2.2",u"REDES DE DISTRIBUCIÓN ",23],
	[u"OE.4.2.3",u"REDES DE ALIMENTACIÓN ",23],
	[u"OE.4.2.4",u"ACCESORIOS DE REDES DE AGUA ",23],
	[u"OE.4.2.5",u"VÁLVULAS",23],
	[u"OE.4.2.6",u"ALMACENAMIENTO DE AGUA ",23],
	[u"OE.4.2.7",u"EQUIPOS Y OTRAS INSTALACIONES ",23],
	[u"OE.4.3.1",u"SALIDA DE AGUA CALIENTE ",24],
	[u"OE.4.3.2",u"REDES DE DISTRIBUCIÓN DE AGUA CALIENTE",24],
	[u"OE.4.3.3",u"ACCESORIOS DE REDES DE AGUA CALIENTE ",24],
	[u"OE.4.3.4",u"VÁLVULAS",24],
	[u"OE.4.3.5",u"EQUIPOS DE PRODUCCIÓN DE AGUA CALIENTE ",24],
	[u"OE.4.4.1",u"REDES DE ALIMENTACIÓN ",25],
	[u"OE.4.4.2",u"ACCESORIOS",25],
	[u"OE.4.4.3",u"SUMINISTRO E INSTALACIÓN DE GABINETES CONTRA INCENDIO ",25],
	[u"OE.4.4.4",u"SUMINISTRO E INSTALACIÓN DE JUNTA ANTI SÍSMICA",25],
	[u"OE.4.4.5",u"VÁLVULAS DE SISTEMA CONTRA INCENDIO ",25],
	[u"OE.4.4.6",u"INSTALACIONES ESPECIALES ",25],
	[u"OE.4.5.1",u"RED DE RECOLECCIÓN ",26],
	[u"OE.4.5.2",u"ACCESORIOS ",26],
	[u"OE.4.6.1",u"SALIDAS DE DESAGÜE ",27],
	[u"OE.4.6.2",u"REDES DE DERIVACIÓN ",27],
	[u"OE.4.6.3",u"REDES COLECTORAS ",27],
	[u"OE.4.6.4",u"ACCESORIOS DE REDES COLECTORAS ",27],
	[u"OE.4.6.5",u"CÁMARAS DE INSPECCIÓN ",27],
	[u"OE.4.6.6",u"INSTALACIONES ESPECIALES ",27],
	[u"OE.5.2.1",u"SALIDA ",30],
	[u"OE.5.2.2",u"CANALIZACIONES, CONDUCTOS O TUBERÍAS ",30],
	[u"OE.5.2.3",u"CONDUCTORES Y CABLES DE ENERGÍA EN TUBERÍAS ",30],
	[u"OE.5.2.4",u"SISTEMAS DE CONDUCTOS ",30],
	[u"OE.5.2.5",u"INSTALACIONES EXPUESTAS ",30],
	[u"OE.5.2.6",u"TABLEROS PRINCIPALES ",30],
	[u"OE.5.2.7",u"TABLERO DE DISTRIBUCIÓN ",30],
	[u"OE.5.2.8",u"DISPOSITIVOS DE MANIOBRA Y PROTECCIÓN ",30],
	[u"OE.5.5.1",u"LÁMPARAS ",33],
	[u"OE.5.5.2",u"REFLECTORES ",33],
	[u"OE.5.6.1",u"BOMBA PARA AGUA ",34],
	[u"OE.5.6.2",u"BOMBAS PARA DESAGÜE (IGUAL A BOMBAS PARA AGUA)",34],
	[u"OE.5.6.3",u"OTRAS BOMBAS",34],
	[u"OE.5.6.4",u"GRUPOS ELECTRÓGENOS ",34],
	[u"OE.5.6.5",u"SISTEMA DE RECIRCULACIÓN ",34],
	[u"OE.5.6.6",u"ASCENSORES Y MONTACARGAS ",34],
	[u"OE.5.6.7",u"SISTEMAS DE PARLANTES ",34],
	[u"OE.5.6.8",u"SISTEMA DE MÚSICA AMBIENTAL ",34],
	[u"OE.5.6.9",u"SISTEMA DE TRADUCCIÓN SIMULTANEA ",34],
	[u"OE.5.6.10",u"SISTEMA DE SEGURIDAD ",34],
	[u"OE.5.6.11",u"PROYECTORES Y PANTALLAS ",34],
	[u"OE.5.6.12",u"CAMPANAS EXTRACTORAS ",34],
	[u"OE.5.6.13",u"SISTEMA DE VAPOR ",34],
	[u"OE.5.6.14",u"SISTEMA DE AIRE COMPRIMIDO ",34],
	[u"OE.5.6.15",u"SISTEMA DE OXÍGENO ",34],
	[u"OE.5.6.16",u"SISTEMA DE VENTILACIÓN MECÁNICA ",34],
	[u"OE.5.6.17",u"SISTEMA DE VACÍO ",34],
	[u"OE.5.6.18",u"SISTEMA DE AIRE ACONDICIONADO ",34],
	[u"OE.6.1.1",u"CABLES EN TUBERÍAS ",35],
	[u"OE.7.1.1",u"TUBERÍA A LA VISTA ",42],
	[u"OE.7.1.2",u"TUBERÍA CON CANALETA O POR CONDUCTO ",42],
	[u"OE.7.1.3",u"TUBERÍA MONTANTE",42],
	[u"OE.7.2.1",u"INSTALACIÓN DE UN ARTEFACTO",43],
	[u"OE.7.2.2",u"CONVERSIÓN DE UN ARTEFACTO ",43],
	[u"OE.7.4.1",u"VENTILACIÓN (SUPERIOR O INFERIOR). ",45],
	[u"OE.7.5.1",u"DUCTOS DE EVACUACIÓN DE HUMOS PARA LOS ARTEFACTOS A GAS. ",46]
]

for codigo3,descripcion3,m2_id in mts3:
	m2 = Metrado2.objects.get(id=m2_id)
	m2.metrado_3.create(codigo=codigo3,descripcion=descripcion3)

mts4 = [[u"OE.1.1.1.1",u"OFICINAS ",1],
	[u"OE.1.1.1.2",u"ALMACENES ",1],
	[u"OE.1.1.1.3",u"CASETAS DE GUARDIANÍA ",1],
	[u"OE.1.1.1.4",u"COMEDORES ",1],
	[u"OE.1.1.1.5",u"VESTUARIOS ",1],
	[u"OE.1.1.1.6",u"SERVICIOS HIGIÉNICOS ",1],
	[u"OE.1.1.1.7",u"CERCOS ",1],
	[u"OE.1.1.1.8",u"CARTELES ",1],
	[u"OE.1.1.2.1",u"INSTALACIONES PROVISIONALES ",2],
	[u"OE.1.1.2.2",u"DESAGÜE PARA LA CONSTRUCCIÓN ",2],
	[u"OE.1.1.2.3",u"ENERGÍA ELÉCTRICA PROVISIONAL ",2],
	[u"OE.1.1.2.4",u"INSTALACIÓN TELEFÓNICA Y COMUNICACIÓN PROVISIONAL ",2],
	[u"OE.1.1.3.1",u"LIMPIEZA DEL TERRENO ",3],
	[u"OE.1.1.4.1",u"TALA DE ÁRBOLES ",4],
	[u"OE.1.1.4.2",u"ELIMINACIÓN DE RAÍCES ",4],
	[u"OE.1.1.4.3",u"ELIMINACIÓN DE ROCAS ",4],
	[u"OE.1.1.4.4",u"ELIMINACIÓN DE ELEMENTOS ENTERRADOS ",4],
	[u"OE.1.1.6.1",u"ELIMINACION DE DEMOLICIONES ",6],
	[u"OE.1.1.9.1",u"TRAZO, NIVELES Y REPLANTEO PRELIMINAR ",9],
	[u"OE.1.1.9.2",u"REPLANTEO DURANTE EL PROCESO ",9],
	[u"OE.1.2.1.1",u"EQUIPOS DE PROTECCIÓN INDIVIDUAL ",10],
	[u"OE.1.2.1.2",u"EQ IPOS DE_PROTECCIÓN COLECTIVA ",10],
	[u"OE.1.2.1.3",u"SENALIZACION TEMPORAL DE SEGURIDAD ",10],
	[u"OE.1.2.1.4",u"CAPACITACIÓN EN SEGURIDAD Y SALUD ",10],
	[u"OE.2.1.1.1",u"NIVELACIÓN. ",12],
	[u"OE.2.1.1.2",u"NIVELADO APISONADO ",12],
	[u"OE.2.1.2.1",u"EXCAVACIONES MASIVAS ",13],
	[u"OE.2.1.2.2",u"EXCAVACIONES SIMPLES ",13],
	[u"OE.2.1.4.1",u"RELLENO CON MATERIAL PROPIO ",15],
	[u"OE.2.1.4.2",u"RELLENOS CON MATERIAL DE PRÉSTAMO ",15],
	[u"OE.2.1.7.1",u"TABLAESTACADO PARA EXCAVACIONES, ESTRUCTURAS, POZOS, CÁMARAS SUBTERRÁNEAS, ETC. ",18],
	[u"OE.2.1.7.1",u"TABLAESTACADO PARA EXCAVACIONES DE ZANJAS",18],
	[u"OE.2.2.2.1",u"PARA EL CONCRETO ",20],
	[u"OE.2.2.2.2",u"PARA EL ENCOFRADO Y DESENCOFRADO ",20],
	[u"OE.2.2.4.1",u"PARA EL CONCRETO ",22],
	[u"OE.2.2.4.2",u"PARA EL ENCOFRADO Y DESENCOFRADO ",22],
	[u"OE.2.2.5.1",u"PARA EL CONCRETO",23],
	[u"OE.2.2.5.2",u"PARA EL ENCOFRADO Y DESENCOFRADO ",23],
	[u"OE.2.2.6.1",u"PARA EL CONCRETO ",24],
	[u"OE.2.2.6.2",u"PARA EL ENCOFRADO Y DESENCOFRADO ",24],
	[u"OE.2.2.7.1",u"PARA EL CONCRETO ",25],
	[u"OE.2.2.7.2",u"PARA EL ENCOFRADO Y DESENCOFRADO EN GRADAS",25],
	[u"OE.2.2.8.1",u"PARA EL CONCRETO ",26],
	[u"OE.2.2.8.2",u"PARA EL ENCOFRADO Y DESENCOFRADO EN RAMPAS ",26],
	[u"OE.2.3.1.1",u"PARA EL CONCRETO ",28],
	[u"OE.2.3.1.2",u"PARA EL ENCOFRADO Y DESENCOFRADO ",28],
	[u"OE.2.3.1.3",u"PARA LA ARMADURA DE ACERO",28],
	[u"OE.2.3.2.1",u"PARA EL CONCRETO ",29],
	[u"OE.2.3.2.2",u"PARA EL ENCOFRADO Y DESENCOFRADO ",29],
	[u"OE.2.3.2.3",u"PARA LA ARMADURA DE ACERO. ",29],
	[u"OE.2.3.3.1",u"PARA EL CONCRETO ",30],
	[u"OE.2.3.3.2",u"PARA EL ENCOFRADO Y DESENCOFRADO ",30],
	[u"OE.2.3.3.3",u"PARA LA ARMADURA DE ACERO ",30],
	[u"OE.2.3.4.1",u"PARA EL CONCRETO ",31],
	[u"OE.2.3.4.2",u"PARA EL ENCOFRADO Y DESENCOFRADO ",31],
	[u"OE.2.3.4.3",u"PARA LA ARMADURA DE ACERO. ",31],
	[u"OE.2.3.5.1",u"PARA EL CONCRETO ",32],
	[u"OE.2.3.5.2",u"PARA EL ENCOFRADO Y DESENCOFRADO ",32],
	[u"OE.2.3.5.3",u"PARA LA ARMADURA DE ACERO. ",32],
	[u"OE.2.3.6.1",u"MUROS DE CONTENCIÓN ",33],
	[u"OE.2.3.6.2",u"MUROS DE CONCRETO, TABIQUES DE CONCRETO Y PLACAS",33],
	[u"OE.2.3.6.3",u"PANTALLAS, BARANDAS Y SIMILARES",33],
	[u"OE.2.3.7.1",u"PARA EL CONCRETO ",34],
	[u"OE.2.3.7.2",u"PARA EL ENCOFRADO Y DESENCOFRADO ",34],
	[u"OE.2.3.7.3",u"PARA LA ARMADURA DE ACERO. ",34],
	[u"OE.2.3.8.1",u"PARA EL CONCRETO ",35],
	[u"OE.2.3.8.2",u"PARA EL ENCOFRADO Y DESENCOFRADO ",35],
	[u"OE.2.3.8.3",u"PARA LA ARMADURA DE ACERO. ",35],
	[u"OE.2.3.9.1",u"LOSAS MACIZAS ",36],
	[u"OE.2.3.9.2",u"LOSAS ALIGERADAS CONVENCIONALES ",36],
	[u"OE.2.3.9.3",u"LOSAS ALIGERADAS CON VIGUETAS PREFABRICADAS",36],
	[u"OE.2.3.9.4",u"LOSAS NERVADAS",36],
	[u"OE.2.3.9.5",u"LOSAS CÁSCARA ",36],
	[u"OE.2.3.9.6",u"LOSA HONGO ",36],
	[u"OE.2.3.9.7",u"LOSAS ESPECIALES ",36],
	[u"OE.2.3.10.1",u"PARA EL CONCRETO ",37],
	[u"OE.2.3.10.2",u"PARA EL ENCOFRADO Y DESENCOFRADO ",37],
	[u"OE.2.3.10.3",u"PARA LA ARMADURA DE ACERO. ",37],
	[u"OE.2.3.11.1",u"PARA EL CONCRETO ",38],
	[u"OE.2.3.11.2",u"PARA EL ENCOFRADO Y DESENCOFRADO ",38],
	[u"OE.2.3.11.3",u"PARA LA ARMADURA DE ACERO. ",38],
	[u"OE.2.3.12.1",u"PARA EL CONCRETO ",39],
	[u"OE.2.3.12.2",u"PARA EL ENCOFRADO Y DESENCOFRADO ",39],
	[u"OE.2.3.12.3",u"PARA LA ARMADURA DE ACERO. ",39],
	[u"OE.2.3.13.1",u"PARA EL CONCRETO ",40],
	[u"OE.2.3.13.2",u"PARA EL ENCOFRADO Y DESENCOFRADO ",40],
	[u"OE.2.3.13.3",u"PARA LA ARMADURA DE ACERO. ",40],
	[u"OE.2.3.14.1",u"PARA LOS PILOTES ",41],
	[u"OE.2.3.15.1",u"PARA CONCRETO ",42],
	[u"OE.2.3.15.2",u"PARA ENCOFRADO ",42],
	[u"OE.2.3.15.3",u"PARA ARMADURA ",42],
	[u"OE.2.3.16.1",u"VIGAS",43],
	[u"OE.2.3.16.2",u"LOSAS ",43],
	[u"OE.2.4.1.1",u"PARA ARMADO ",45],
	[u"OE.2.4.1.2",u"PARA MONTAJE ",45],
	[u"OE.2.4.2.1",u"PARA ARMADO ",46],
	[u"OE.2.4.2.2",u"PARA MONTAJE ",46],
	[u"OE.2.4.3.1",u"PARA ARMADO ",47],
	[u"OE.2.4.3.2",u"PARA MONTAJE ",47],
	[u"OE.2.4.4.1",u"PARA ARMADO ",48],
	[u"OE.2.4.4.2",u"PARA MONTAJE ",48],
	[u"OE.2.4.5.1",u"PARA ARMADO ",49],
	[u"OE.2.4.5.2",u"PARA MONTAJE ",49],
	[u"OE.2.4.6.1",u"CON PLANCHAS CORRUGADAS GALVANIZADAS ",50],
	[u"OE.2.4.6.2",u"CON PLANCHAS CORRUGADAS DE FIBRO-CEMENTO. ",50],
	[u"OE.2.4.6.3",u"CON PLANCHAS CORRUGADAS DE ALUMINIO. ",50],
	[u"OE.2.4.6.4",u"CON PLANCHAS CORRUGADAS PLÁSTICAS. ",50],
	[u"OE.2.4.6.5",u"CON TEJAS. ",50],
	[u"OE.2.4.6.6",u"CON LADRILLOS DE VIDRIO. ",50],
	[u"OE.2.4.6.7",u"CON VIDRIO. ",50],
	[u"OE.2.4.7.1",u"PARA CUMBRERAS ",51],
	[u"OE.2.4.7.2",u"A CANALETAS ",51],
	[u"OE.2.4.7.3",u"PARA BAJANTES ",51],
	[u"OE.2.5.5.1",u"CON PLANCHAS CORRUGAS GALVANIZADAS. ",56],
	[u"OE.2.5.5.2",u"CON PLANCHAS CORRUGADAS DE FIBRO-CEMENTO. ",56],
	[u"OE.2.5.5.3",u"CON PLANCHAS CORRUGADAS DE ALUMINIO. ",56],
	[u"OE.2.5.5.4",u"CON PLANCHAS CORRUGADAS PLÁSTICAS. ",56],
	[u"OE.2.5.5.5",u"CON TEJAS. ",56],
	[u"OE.2.5.5.6",u"CON MADERA. ",56],
	[u"OE.2.5.5.7",u"CON DIVERSAS PLANCHAS LISAS. ",56],
	[u"OE.3.2.16.1",u"ENLUCIDO DE YESO SOBRE MUROS DE ADOBE ",92],
	[u"OE.3.2.16.2",u"ENLUCIDO DE YESO SOBRE MUROS DE CONCRETO ",92],
	[u"OE.3.2.16.3",u"ENLUCIDO DE YESO SOBRE MUROS DE LADRILLO ",92],
	[u"OE.3.2.24.1",u"SOLAQUEO DE MUROS ",101],
	[u"OE.3.3.6.1",u"DE MALLA METÁLICA ",107],
	[u"OE.3.3.6.2",u"DE PANELES ",107],
	[u"OE.3.4.2.1",u"LOSETA CORRIENTE ",109],
	[u"OE.3.4.2.2",u"LOSETA VENECIANA ",109],
	[u"OE.3.4.2.3",u"LOSETA TIPO CORCHO ",109],
	[u"OE.3.4.2.4",u"LOSETA DE MÁRMOL RECONSTRUIDO ",109],
	[u"OE.3.4.2.5",u"LOSETAS DE CANTO RODADO ",109],
	[u"OE.3.4.2.6",u"LOSETAS DE ACABADOS ESPECIALES ",109],
	[u"OE.3.4.2.7",u"BALDOSA ASFÁLTICA",109],
	[u"OE.3.4.2.8",u"BALDOSA VINiLICA ",109],
	[u"OE.3.4.2.9",u"TERRAZO ",109],
	[u"OE.3.4.2.10",u"MÁRMOL ",109],
	[u"OE.3.4.2.11",u"MAYÓLICA ",109],
	[u"OE.3.4.2.12",u"PE PELMA ",109],
	[u"OE.3.4.2.13",u"CANTOS RODADOS ",109],
	[u"OE.3.4.2.14",u"GRANITO LAVADO ",109],
	[u"OE.3.4.2.15",u"LAJA ",109],
	[u"OE.3.4.2.16",u"MADERA MACHIHEMBRADA ",109],
	[u"OE.3.4.2.17",u"PARQUET ",109],
	[u"OE.3.4.2.18",u"IMITACIÓN MADERA ",109],
	[u"OE.3.4.2.19",u"PISOS LAMINADOS ",109],
	[u"OE.3.4.2.20",u"PORCELANATOS",109],
	[u"OE.3.4.2.21",u"CERÁMICOS ",109],
	[u"OE.3.4.2.22",u"LOSETAS DE CEMENTO ",109],
	[u"OE.3.4.2.23",u"OTROS ",109],
	[u"OE.3.5.1.1",u"PEPELMA ",116],
	[u"OE.3.5.1.2",u"MÁRMOL ",116],
	[u"OE.3.5.1.3",u"GRANITO ARTIFICIAL ",116],
	[u"OE.3.5.1.4",u"DE CEMENTO SIMPLE ",116],
	[u"OE.3.5.1.5",u"DE CANTOS RODADOS ",116],
	[u"OE.3.5.1.6",u"DE MADERA ",116],
	[u"OE.3.5.1.7",u"DE PLANCHAS PLÁSTICAS ",116],
	[u"OE.3.5.1.8",u"DE LADRILLOS DECORATIVOS ",116],
	[u"OE.3.5.1.9",u"REVESTIMIENTO ESPECIALES ",116],
	[u"OE.3.5.1.10",u"PORCELANATO",116],
	[u"OE.3.5.1.11",u"CERÁMICO ",116],
	[u"OE.3.5.1.12",u"ALUMINIO ",116],
	[u"OE.3.5.1.13",u"OTROS ",116],
	[u"OE.3.5.2.1",u"LOSETA ",117],
	[u"OE.3.5.2.2",u"GRANITO VACIADO EN OBRA",117],
	[u"OE.3.5.2.3",u"CEMENTO",117],
	[u"OE.3.5.2.4",u"VINÍLICO ",117],
	[u"OE.3.5.2.5",u"ALUMINIO ",117],
	[u"OE.3.5.2.6",u"MÁRMOL ",117],
	[u"OE.3.5.2.7",u"MADERA ",117],
	[u"OE.3.5.2.8",u"PORCELANATO ",117],
	[u"OE.3.5.2.9",u"CERÁMICO ",117],
	[u"OE.3.5.2.10",u"ACERO INOXIDABLE ",117],
	[u"OE.3.5.2.11",u"OTROS ",117],
	[u"OE.4.6.5.1",u"PARA CAJAS DE REGISTRO ",208],
	[u"OE.4.6.5.2",u"PARA BUZONES. ",208]
]
for codigo4,descripcion4,m3_id in mts4:
	m3 = Metrado3.objects.get(id=m3_id)
	m3.metrado_4.create(codigo=codigo4,descripcion=descripcion4)
